---
- name: Validate all
  hosts: all
  gather_facts: no
  tasks:
    - name: Validate Input Data
      run_once: yes
      assert:
        that:
          - app_name is defined
        fail_msg: "Please include all required Parameters"

- name: Deploy Apps
  hosts: "{{ app_name }}"
  tasks:
  
    - debug: var=password

    - name: Load App Varaibles
      import_role:
        name: load_app_vars

    - name: DEBUG Overalpping Groups Vars
      debug:
        msg:
          - "sudo_user: {{ sudo_user }}"
          - "db_uid: {{ db_uid }}"

    # - name: DEBUG Groups Vars
    #   when: mongo_db is defined
    #   debug:
    #     msg:
    #       - "mongo_db: {{ mongo_db }}"

    # - name: DEBUG Groups Vars
    #   when: psql_db is defined
    #   debug:
    #     msg:
    #       - "psql_db: {{ psql_db }}"